### ISSUE TITLE
After successful recognition it crashes Node Red

### ISSUE THREAD

**Issue by WhiteLionATX** [johanneskropf/node-red-contrib-personal-wake-word#3]
After a wake word ist recognized (Debug node output is good) it throws an error which leads to a Node Red restart:
`20 Oct 15:02:06 - TypeError: Cannot read property 'destroy' of null
    at Timeout.node.recoverTimeout.setTimeout [as _onTimeout] (/home/pi/.node-red/node_modules/node-red-contrib-personal-wake-word/wakeword.js:173:31)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
nodered.service: Main process exited, code=exited, status=1/FAILURE
nodered.service: Failed with result 'exit-code'.
nodered.service: Service RestartSec=20s expired, scheduling restart.
nodered.service: Scheduled restart job, restart counter is at 1.
Stopped Node-RED graphical event wiring tool.
Started Node-RED graphical event wiring tool.
20 Oct 15:02:28 - [info]
Welcome to Node-RED
`

My test flow:
`[{"id":"405f54f28edcc1e4","type":"debug","z":"59c97e7d58b1868b","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":770,"y":720,"wires":[]},{"id":"d1b89be9bbb75fa4","type":"debug","z":"59c97e7d58b1868b","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":770,"y":680,"wires":[]},{"id":"769a36bc3b10b3ee","type":"file in","z":"59c97e7d58b1868b","name":"","filename":"/home/pi/wakeword/p1.wav","format":"","chunk":false,"sendError":false,"encoding":"none","allProps":false,"x":460,"y":660,"wires":[["0c6d034fd198d68d"]]},{"id":"0c19d0987fd5f105","type":"inject","z":"59c97e7d58b1868b","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":520,"y":620,"wires":[["769a36bc3b10b3ee"]]},{"id":"0c6d034fd198d68d","type":"wake-word","z":"59c97e7d58b1868b","wakeword":"463b9304e87f0a31","threshold":0.5,"averaging":true,"inputProp":"payload","outputProp":"payload","controlProp":"control","passthrough":false,"name":"","x":510,"y":700,"wires":[["d1b89be9bbb75fa4"],["405f54f28edcc1e4"]]},{"id":"463b9304e87f0a31","type":"wakeword-config","name":"pipsi","files":["/home/pi/wakeword/p1.wav","/home/pi/wakeword/p2.wav","/home/pi/wakeword/p3.wav"]}]`

**Comment by johanneskropf** [comment]
Hello,
I couldn't reproduce your bug on any of my test systems.
But I have just added some extra error handling that should prevent node-red from crashing anyway.
Could you please update to 0.2.7 either from npm or github and report back if this fixes you problem?

**Comment by WhiteLionATX** [comment]
Thanx 4 ur fast reply ! I did update to 0.2.7. Now it does not crash NR anymore but stops listening. This is the output:
`20 Oct 17:11:42 - [warn] [wake-word:0c6d034fd198d68d] ready
20 Oct 17:11:52 - [warn] [wake-word:0c6d034fd198d68d] something went wrong after detection, trying to recover
20 Oct 17:12:49 - [warn] [wake-word:0c6d034fd198d68d] ready
20 Oct 17:12:53 - [warn] [wake-word:0c6d034fd198d68d] ready
20 Oct 17:13:03 - [warn] [wake-word:0c6d034fd198d68d] ready
20 Oct 17:13:13 - [warn] [wake-word:0c6d034fd198d68d] something went wrong after detection, trying to recover
20 Oct 17:13:21 - [warn] [wake-word:0c6d034fd198d68d] ready
20 Oct 17:13:32 - [warn] [wake-word:0c6d034fd198d68d] something went wrong after detection, trying to recover
`
I clicked a view times ;)

**Comment by johanneskropf** [comment]
What system is this running on and can you post your flow?
The warning that something is wrong after detection happens when the wake-word listener needs more than 10 seconds to be ready again after a detection.
This can happen on sometimes on something like a pi 3 a+ but normally not everytime.
But even so it than trys to restart the listener and once ready should listen again automatically.

**Comment by WhiteLionATX** [comment]
the flow is posted at initial post of this thread. There a 3 wav s of the wake words (p1.wav, p2....) and as testing p1.wav is taken to trigger.
I ve running it on a raspberry pi 4. does not get to "starting detector" even after 1 minute.

UPDATE: Ok, it may be wrong to use a "file in node" as it works with "sox record node" without a crash after detection.

**Comment by johanneskropf** [comment]
Yes the wakeword listener is not made for file input. Its is purely made to listen to a continuous stream of audio buffers.

**Comment by WhiteLionATX** [comment]
ok, I am sorry!
